[metadata]
name = SQLAero
version = 0.1.0a1
author = Jiefu Chen
author_email = keppa1991@163.com
description = Fast MySQL driver build in Cython (Sync and Async).
long_description = file: README.md
long_description_content_type = text/markdown
keywords = mysql, mariadb, pymysql, aiomysql, cython, asyncio
license = MIT license
classifiers =
    Development Status :: 3 - Alpha
    Programming Language :: Python :: 3.13
    Programming Language :: Python :: Implementation :: CPython
    Operating System :: MacOS :: MacOS X

[options]
zip_safe = False
include_package_data = True
package_dir =
    = src
packages = find:
python_requires = >=3.13,<3.14
install_requires =
    cytimes>=3.1.0
    numpy>=1.25.2
    orjson>=3.10.2
    pandas<3.0.0
    typing-extensions>=4.9.0
    
[options.packages.find]
where = src

[build_ext]
inplace=0